/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("java")

    id("com.github.johnrengelman.shadow") version "8.1.1"
    id("com.lielamar.java-conventions")
}

dependencies {
    compileOnly("org.spigotmc:spigot-api:1.20.4-R0.1-SNAPSHOT")

    compileOnly(project(":2fa-core"))
}

description = "2fa-api"
