# Regular Libs
jetbrainsVersion=26.0.2
jsonVersion=20250517
slf4jVersion=2.0.17
log4jVersion=2.25.0
espressoVersion=ed830513b6
micronautVersion=4.9.3
minecraftVersion=1.21.6-R0.1-SNAPSHOT
bungeeVersion=1.21-R0.4-SNAPSHOT
placeholderapiVersion=2.11.6
caffeineVersion=3.2.1
atlassianOnetimeVersion=2.1.2
commonsCodecVersion=1.18.0

# Databases
hikariVersion=6.3.0
h2Version=2.3.232
mysqlVersion=9.3.0
postgresVersion=42.7.7
mariadbVersion=3.5.3
mongodbVersion=5.5.1