name: 2FA
version: "1.4.0"
authors: [LielAmar]
main: com.lielamar.auth.bukkit.TwoFactorAuthentication
description: Add another layer of protection to your server

commands:
  2fa:
    description: Main 2FA Command
    aliases: [auth]

permissions:
  2fa.*:
    description: Permissions to all 2FA commands
    default: op
    children:
      2fa.use: true
      2fa.help: true
      2fa.remove: true
      2fa.remove.others: true
      2fa.reload: true
  2fa.use:
    description: Permissions to use the /2FA command
    default: op
  2fa.help:
    description: Permissions to view the help page
    default: op
  2fa.remove:
    description: Permissions to remove your own 2FA
    default: op
  2fa.remove.others:
    description: Admin permissions to remove other players' 2FA
    default: op
  2fa.reload:
    description: Admin permissions to reload the 2FA plugin
    default: op
  2fa.demand:
    description: A player with this permission must have 2FA linked to thier account
    default: false