/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("java")

    id("regular-libs")
}

val bungeeVersion: String by project
val micronautVersion: String by project

dependencies {
    compileOnly("net.md-5:bungeecord-api:$bungeeVersion")
    compileOnly("io.micronaut:micronaut-inject-java:$micronautVersion")

    compileOnly(project(":2fa-api"))
    compileOnly(project(":2fa-core"))
}

description = "2fa-bungee"
