/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    `java-library`
    `maven-publish`
}

repositories {
    mavenCentral()
    maven("https://hub.spigotmc.org/nexus/content/repositories/snapshots/")
    maven("https://oss.sonatype.org/content/repositories/snapshots")
    maven("https://repo.velocitypowered.com/snapshots/")
    maven("https://repo.extendedclip.com/content/repositories/placeholderapi/")
    maven("https://jitpack.io")
}

val jetbrainsVersion: String by project
val jsonVersion: String by project
val slf4jVersion: String by project
val log4jVersion: String by project
val espressoVersion: String by project

dependencies {
    compileOnly("org.jetbrains:annotations:$jetbrainsVersion")

    compileOnly("org.json:json:$jsonVersion")

    compileOnly("org.slf4j:slf4j-api:$slf4jVersion")
    compileOnly("org.apache.logging.log4j:log4j-core:$log4jVersion")

    implementation("com.github.DirtyConcept:Espresso:$espressoVersion")
}

group = "com.lielamar"
version = "2.0"
java.sourceCompatibility = JavaVersion.VERSION_17

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile> {
    options.encoding = "UTF-8"
}
