/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("java")

    id("regular-libs")
}

val minecraftVersion: String by project
val micronautVersion: String by project

dependencies {
    compileOnly("org.spigotmc:spigot-api:$minecraftVersion")
    compileOnly("io.micronaut:micronaut-inject-java:$micronautVersion")

    compileOnly("me.clip:placeholderapi:2.11.6")

    compileOnly(project(":2fa-api"))
    compileOnly(project(":2fa-core"))
}

description = "2fa-bukkit"
