/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("java")

    id("com.lielamar.java-conventions")
}

dependencies {
    compileOnly("org.json:json:20240303")

    compileOnly("org.spigotmc:spigot-api:1.21-R0.1-SNAPSHOT")
    compileOnly("io.micronaut:micronaut-inject-java:4.5.3")

    compileOnly("me.clip:placeholderapi:2.11.6")

    compileOnly("org.slf4j:slf4j-api:2.0.12")
    compileOnly("org.apache.logging.log4j:log4j-core:2.23.1")

    compileOnly(project(":2fa-api"))
    compileOnly(project(":2fa-core"))
}

description = "2fa-bukkit"
