/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    java

    id("com.gradleup.shadow") version "8.3.6"
    id("database-libs")
}

val jsonVersion: String by project
val micronautVersion: String by project
val caffeineVersion: String by project
val atlassianOnetimeVersion: String by project
val commonsCodecVersion: String by project

dependencies {
    implementation(project(":2fa-api"))

    implementation("org.json:json:$jsonVersion")
    annotationProcessor("io.micronaut:micronaut-inject-java:$micronautVersion")
    api("io.micronaut:micronaut-inject-java:$micronautVersion")

    compileOnly("com.github.ben-manes.caffeine:caffeine:${caffeineVersion}")
    compileOnly("com.atlassian:onetime:${atlassianOnetimeVersion}")
    compileOnly("commons-codec:commons-codec:${commonsCodecVersion}")

}

description = "2fa-core"
